name: Build/release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    if: ${{ github.event.base_ref == 'refs/heads/master' || github.event.base_ref == 'refs/heads/production' }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - name: Build for production release
        if: github.event.base_ref == 'refs/heads/production'
        run: yarn build
      - name: Build for staging release
        if: github.event.base_ref == 'refs/heads/master'
        run: yarn build-staging
      - name: 'Upload to Google Cloud'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: 'dist'
          destination: ${{ (github.event.base_ref == 'refs/heads/production' && 'electron-upload-bucket/desktop') || 'electron-upload-bucket/desktop-staging' }}
          parent: false
